apiVersion: 1

policies:
  - orgId: 1
    receiver: webhook
    group_by:
      - grafana_folder
      - alertname
      - target
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 2h
    mute_time_intervals: []
